name: Release

on:
  push:
    branches: [main]

permissions: {}

jobs:
  release:
    uses: release-baton/release-baton/.github/workflows/release-please.yml@ab5434d252b3c7e7fd57abe6a2e611f04c25213b # v1.2.0
    secrets:
      client-id: ${{ secrets.RELEASE_BATON_CLIENT_ID }}
      app-private-key: ${{ secrets.RELEASE_BATON_PRIVATE_KEY }}
